apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-app
  namespace: airbnb-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-app
  template:
    metadata:
      labels:
        app: odoo-app
    spec:
      containers:
      - name: odoo
        image: odoo:16.0
        ports:
        - containerPort: 8069
        env:
        - name: HOST
          value: "postgres-svc.airbnb-dev.svc.cluster.local"
        - name: USER
          valueFrom:
            secretKeyRef:
              name: odoo-db-secret
              key: USER
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo-db-secret
              key: PASSWORD