apiVersion: v1
kind: Secret
metadata:
  name: odoo-db-secret
  namespace: airbnb-dev
type: Opaque
stringData:
  # Em produção real usarias random_password do terraform, 
  # aqui simplificamos para o projeto académico.
  USER: odoo
  PASSWORD: odoo_password_strong
  DB: odoo_db