apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo-ingress
  namespace: airbnb-prod
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - odoo.prod.airbnb.local
    secretName: odoo-tls-secret
  rules:
  - host: odoo.prod.airbnb.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: odoo-svc
            port:
              number: 80